backend:
  name: github
  branch: main # Branch to update (optional; defaults to master)
  repo: SadowyKinga/Gatsby-Gitbook

  # These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploadscollections:
collections:
  - name: documentation
    label: "documentation"
    folder: content
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Position, widget: number }
      - { name: body, label: Body, widget: markdown }
  - label: "Folder"
    name: "document"
    folder: "content/test1"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: sidebar_position, label: Position, widget: number }
      - { name: body, label: Body, widget: markdown }
